spring:
#  profiles:
#    include: oauth

  datasource:
    url: jdbc:h2:mem:test
    username: Sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.naver.com
    port: 465
    username: ENC(VjnM+wDg8lmtHcsk8QE9ECyZJYbH6R+5t5WyYDnFnWYNcb6Mw3yH0ksvC/MUed2laFNHUTlkIP/JHcHfvx8H0Q==)
    password: ENC(CKqFnC3DcwpqaKq0jBK/xhV/gKlKk/iyKVGvnya9ci/cPhvn3XMDvXHcGBNKYYbl)

  jwt:
    secret: ENC(ZXEtGqwnuaYfyjUWS/iWRZkktb2Ss56OgHnVYkxCcGs2ssDuRxp3dVL9LKiuHFZhHCeaqJ9FabAu1AdY+ftwibqg6dJVsksrA3L/97CP8UZKERFARHbNkrZrC18vpmVk4I+MFTD0mjF/vzS6ovMmiA==)

  h2:
    console:
      enabled: true


logging:
  level:
    org.hibernate.SQL: debug

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

api-tour:
  serviceKey_De: ENC(3SzgxeuP3eeWeiG/75OE8ty6Mui62F+BS5NxlCqR8sDVsXiStFC9l/OBLluPArT9eKgniSe60eHNF1cjSfPJP3lY3CT/j2O7JaCHGduikrkvq5v7Srniu56b9VtituBR8WCtIn7PsRSY5xB43ZMGtfwb1p/fqLKmHT+uSp8GmR4=)
  serviceKey_En: ENC(HeTEumUNsoaqDdFLWs+jzvcpGOSL0IRU6cBJ07ht5fg1scIxGLDmyHCAyOprga8a03oxy+KgkSqKCa3cwh+oZleNJaTuJ+oKvpadQiAt5woMHDdoMVQzDLW3hQNIvaGHsYwoAPl7DMJQ/wLFH27fG4bszTYUbdRlBf5C2qk33JY=)
