spring:
  profiles:
    include: oauth

  datasource:
    url: jdbc:mariadb://localhost:3306/travel
    username: root
    password: 1q!1q!
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true


  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.naver.com
    port: 465
    username: ENC(VjnM+wDg8lmtHcsk8QE9ECyZJYbH6R+5t5WyYDnFnWYNcb6Mw3yH0ksvC/MUed2laFNHUTlkIP/JHcHfvx8H0Q==)
    password: ENC(CKqFnC3DcwpqaKq0jBK/xhV/gKlKk/iyKVGvnya9ci/cPhvn3XMDvXHcGBNKYYbl)

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

  logging:
    level:
      com.minizin.travel.config: INFO
      root: INFO
    file:
      name: logs/myapp.log
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %class{50}.%M:%line - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50}:%line - %msg%n"
    org:
      springframework:
        security: INFO
        web: INFO
        beans.factory: INFO
      hibernate:
        SQL: DEBUG
        type:
          descriptor.sql.BasicBinder: INFO
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
server:
  forward-headers-strategy: framework

api-tour:
  serviceKey_De: K9eWaIkQyqUUDZPWH+jI2Br1awNS1WaksaOZ6EiUbWTEzpVBeXnhTuPjni4n6auCsAUANYZ5o3Q89TF0sFU4bA==
  serviceKey_En: K9eWaIkQyqUUDZPWH%2BjI2Br1awNS1WaksaOZ6EiUbWTEzpVBeXnhTuPjni4n6auCsAUANYZ5o3Q89TF0sFU4bA%3D%3D
