spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: 3d90bb75347bd4b5962a422915dcad90
            client-secret: yaE467VCfY8VKFrmiqOBWD6YCVG6BGhZ
            client-authentication-method: client_secret_post
            redirect-uri: https://lyckabc.synology.me:23080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id